"""Adiciona coluna de senha em texto plano para cliente

Revision ID: 04ecd3f8e03e
Revises: 7b0d3693daa6
Create Date: 2025-11-01 12:03:05.961002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ecd3f8e03e'
down_revision = '7b0d3693daa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_plana_temporaria', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('senha_plana_temporaria')

    # ### end Alembic commands ###
