"""desabilitar datas incluido

Revision ID: 1ff6a796a88a
Revises: 91e9f4f23471
Create Date: 2025-10-08 09:47:55.003469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff6a796a88a'
down_revision = '91e9f4f23471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiencia_profissional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desabilitar_datas', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiencia_profissional', schema=None) as batch_op:
        batch_op.drop_column('desabilitar_datas')

    # ### end Alembic commands ###
