"""criado classe contrato e form

Revision ID: 3d04be459834
Revises: d535b3934136
Create Date: 2025-10-08 13:34:51.789224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d04be459834'
down_revision = 'd535b3934136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locador_nome', sa.String(length=120), nullable=False),
    sa.Column('locador_rg', sa.String(length=20), nullable=True),
    sa.Column('locador_cpf', sa.String(length=20), nullable=True),
    sa.Column('locador_endereco', sa.String(length=200), nullable=True),
    sa.Column('locatario_nome', sa.String(length=120), nullable=False),
    sa.Column('locatario_rg', sa.String(length=20), nullable=True),
    sa.Column('locatario_cpf', sa.String(length=20), nullable=True),
    sa.Column('locatario_endereco', sa.String(length=200), nullable=True),
    sa.Column('endereco_imovel', sa.String(length=200), nullable=False),
    sa.Column('finalidade', sa.String(length=100), nullable=True),
    sa.Column('prazo_meses', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor_aluguel', sa.Float(), nullable=True),
    sa.Column('dia_pagamento', sa.Integer(), nullable=True),
    sa.Column('indice_reajuste', sa.String(length=50), nullable=True),
    sa.Column('multa_percentual', sa.Integer(), nullable=True),
    sa.Column('juros_percentual', sa.Integer(), nullable=True),
    sa.Column('cidade_foro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('data_assinatura', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contrato')
    # ### end Alembic commands ###
