"""Adiciona tabela de configuracao da loja

Revision ID: 43ddbc24a69f
Revises: 7b4a88fccbfd
Create Date: 2025-10-11 16:36:36.545854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ddbc24a69f'
down_revision = '7b4a88fccbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_loja', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('logomarca', sa.String(length=100), nullable=True),
    sa.Column('texto_garantia', sa.Text(), nullable=True),
    sa.Column('email_contato', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao')
    # ### end Alembic commands ###
