"""foto no Orcamento

Revision ID: 65fbf59df01b
Revises: e622136d1846
Create Date: 2025-10-01 11:55:33.481729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65fbf59df01b'
down_revision = 'e622136d1846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.alter_column('data_de_criacao',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.alter_column('data_de_criacao',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
