"""Adiciona tabelas Impressora e RecursoImpressora

Revision ID: 6efe3fbc42a2
Revises: 43ddbc24a69f
Create Date: 2025-10-31 13:28:41.720145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efe3fbc42a2'
down_revision = '43ddbc24a69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impressora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo')
    )
    op.create_table('recurso_impressora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('impressora_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sistema_operacional', sa.String(length=50), nullable=True),
    sa.Column('link_download', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['impressora_id'], ['impressora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurso_impressora')
    op.drop_table('impressora')
    # ### end Alembic commands ###
