"""criacao inicial do banco completo

Revision ID: 71f4f6dccc9e
Revises: 
Create Date: 2026-01-13 09:52:01.742425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f4f6dccc9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('username_cliente', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('telefone_celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_auxiliar', sa.String(length=20), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=True),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.Column('senha_plana_temporaria', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username_cliente')
    )
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_loja', sa.String(length=100), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('logomarca', sa.String(length=100), nullable=True),
    sa.Column('texto_garantia', sa.Text(), nullable=True),
    sa.Column('email_contato', sa.String(length=100), nullable=True),
    sa.Column('site', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locador_nome', sa.String(length=120), nullable=False),
    sa.Column('locador_rg', sa.String(length=20), nullable=True),
    sa.Column('locador_cpf', sa.String(length=20), nullable=True),
    sa.Column('locador_endereco', sa.String(length=200), nullable=True),
    sa.Column('locatario_nome', sa.String(length=120), nullable=False),
    sa.Column('locatario_rg', sa.String(length=20), nullable=True),
    sa.Column('locatario_cpf', sa.String(length=20), nullable=True),
    sa.Column('locatario_endereco', sa.String(length=200), nullable=True),
    sa.Column('endereco_imovel', sa.String(length=200), nullable=False),
    sa.Column('finalidade', sa.String(length=100), nullable=True),
    sa.Column('prazo_meses', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor_aluguel', sa.Float(), nullable=True),
    sa.Column('dia_pagamento', sa.Integer(), nullable=True),
    sa.Column('indice_reajuste', sa.String(length=50), nullable=True),
    sa.Column('multa_percentual', sa.Integer(), nullable=True),
    sa.Column('juros_percentual', sa.Integer(), nullable=True),
    sa.Column('cidade_foro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('data_assinatura', sa.Date(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curriculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('estado_civil', sa.String(length=30), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('telefone_principal', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impressora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo')
    )
    op.create_table('peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_peca', sa.String(length=100), nullable=False),
    sa.Column('detalhes_opcional', sa.Text(), nullable=True),
    sa.Column('codigo_interno', sa.String(length=100), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_peca', name='uq_peca_nome')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao_servico', sa.String(length=150), nullable=False),
    sa.Column('detalhes_opcional', sa.Text(), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao_servico', name='uq_servico_descricao')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cliente_impressora',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('impressora_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['impressora_id'], ['impressora.id'], ),
    sa.PrimaryKeyConstraint('cliente_id', 'impressora_id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('curriculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curriculo_id'], ['curriculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiencia_profissional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=120), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_demissao', sa.Date(), nullable=True),
    sa.Column('desabilitar_datas', sa.Boolean(), nullable=True),
    sa.Column('periodo', sa.Text(), nullable=True),
    sa.Column('curriculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curriculo_id'], ['curriculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formacao_academica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('curriculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curriculo_id'], ['curriculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero_orcamento', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('equipamento', sa.String(length=150), nullable=False),
    sa.Column('numero_de_serie', sa.String(length=100), nullable=True),
    sa.Column('validade_do_orcamento', sa.String(length=10), nullable=True),
    sa.Column('problema_informado', sa.Text(), nullable=False),
    sa.Column('problema_constatado', sa.Text(), nullable=False),
    sa.Column('observacoes_cliente', sa.Text(), nullable=True),
    sa.Column('observacoes_internas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tecnico_responsavel', sa.String(length=50), nullable=True),
    sa.Column('data_de_criacao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurso_impressora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('impressora_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sistema_operacional', sa.String(length=50), nullable=True),
    sa.Column('link_download', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['impressora_id'], ['impressora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_orcamento_peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_cobrado', sa.Float(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('peca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['peca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_orcamento_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_cobrado', sa.Float(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('numero_sequencial', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('equipamento', sa.String(length=150), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('numero_de_serie', sa.String(length=100), nullable=True),
    sa.Column('tecnico_responsavel', sa.String(length=50), nullable=True),
    sa.Column('defeito', sa.Text(), nullable=False),
    sa.Column('problema_constatado', sa.Text(), nullable=True),
    sa.Column('servico_executado', sa.Text(), nullable=True),
    sa.Column('observacoes_cliente', sa.Text(), nullable=True),
    sa.Column('observacoes_internas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orcamento_id')
    )
    op.create_table('foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=20), nullable=True),
    sa.Column('legenda', sa.String(length=150), nullable=True),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_cobrado', sa.Float(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('peca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['peca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_cobrado', sa.Float(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_servico')
    op.drop_table('item_peca')
    op.drop_table('foto')
    op.drop_table('ordem_servico')
    op.drop_table('item_orcamento_servico')
    op.drop_table('item_orcamento_peca')
    op.drop_table('recurso_impressora')
    op.drop_table('orcamento')
    op.drop_table('formacao_academica')
    op.drop_table('experiencia_profissional')
    op.drop_table('curso')
    op.drop_table('cliente_impressora')
    op.drop_table('usuario')
    op.drop_table('servico')
    op.drop_table('peca')
    op.drop_table('impressora')
    op.drop_table('curriculo')
    op.drop_table('contrato')
    op.drop_table('configuracao')
    op.drop_table('cliente')
    # ### end Alembic commands ###
