"""Adiciona permissao de acesso a resets para Cliente

Revision ID: 7b0d3693daa6
Revises: 6efe3fbc42a2
Create Date: 2025-10-31 13:53:03.743300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0d3693daa6'
down_revision = '6efe3fbc42a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tem_acesso_resets', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('tem_acesso_resets')

    # ### end Alembic commands ###
