"""Adiciona tabela de cursos

Revision ID: 7b4a88fccbfd
Revises: df846332bcec
Create Date: 2025-10-09 12:21:20.106585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4a88fccbfd'
down_revision = 'df846332bcec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('curriculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curriculo_id'], ['curriculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curso')
    # ### end Alembic commands ###
