"""Adciona periodo a esperiencia

Revision ID: 91e9f4f23471
Revises: 307986f1f8ac
Create Date: 2025-10-08 09:21:59.359517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e9f4f23471'
down_revision = '307986f1f8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiencia_profissional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiencia_profissional', schema=None) as batch_op:
        batch_op.drop_column('periodo')

    # ### end Alembic commands ###
