"""criado ItemOS e seus relacionamentos

Revision ID: a087911993b5
Revises: aec92b491b01
Create Date: 2025-09-22 17:14:19.935959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a087911993b5'
down_revision = 'aec92b491b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_cobrado', sa.Float(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_os')
    # ### end Alembic commands ###
