"""Implementa acesso granular a resets

Revision ID: aba4c551ea3b
Revises: 04ecd3f8e03e
Create Date: 2025-11-01 18:59:25.405288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba4c551ea3b'
down_revision = '04ecd3f8e03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_impressora',
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('impressora_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['impressora_id'], ['impressora.id'], ),
    sa.PrimaryKeyConstraint('cliente_id', 'impressora_id')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('tem_acesso_resets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tem_acesso_resets', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))

    op.drop_table('cliente_impressora')
    # ### end Alembic commands ###
