"""Cria tabelas Servico e Peca com constraints nomeadas

Revision ID: aec92b491b01
Revises: db39a6e15121
Create Date: 2025-09-22 16:38:54.783288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec92b491b01'
down_revision = 'db39a6e15121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peca', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_peca_nome', ['nome_peca'])

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.alter_column('descricao_servico',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('unidade_medida',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_servico_descricao', ['descricao_servico'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_constraint('uq_servico_descricao', type_='unique')
        batch_op.alter_column('unidade_medida',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.alter_column('descricao_servico',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('peca', schema=None) as batch_op:
        batch_op.drop_constraint('uq_peca_nome', type_='unique')

    # ### end Alembic commands ###
