"""Cria modelos iniciais do curriculo

Revision ID: b00651fb7f99
Revises: b453cb114f1f
Create Date: 2025-10-03 13:42:56.106692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00651fb7f99'
down_revision = 'b453cb114f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('estado_civil', sa.String(length=30), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('telefone_principal', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('objetivo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiencia_profissional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=120), nullable=True),
    sa.Column('cargo', sa.String(length=120), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('data_demissao', sa.Date(), nullable=True),
    sa.Column('curriculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curriculo_id'], ['curriculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formacao_academica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('curriculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curriculo_id'], ['curriculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formacao_academica')
    op.drop_table('experiencia_profissional')
    op.drop_table('curriculo')
    # ### end Alembic commands ###
