"""criado role para usuario e cliente

Revision ID: b43825331b68
Revises: d4f99cd2da86
Create Date: 2025-09-23 19:38:58.719387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43825331b68'
down_revision = 'd4f99cd2da86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
