"""Adiciona campos detalhados a OrdemServico

Revision ID: b453cb114f1f
Revises: ebcaee64fe51
Create Date: 2025-10-01 13:45:48.975825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b453cb114f1f'
down_revision = 'ebcaee64fe51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_de_serie', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tecnico_responsavel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('problema_constatado', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('servico_executado', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observacoes_cliente', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observacoes_internas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordem_servico', schema=None) as batch_op:
        batch_op.drop_column('observacoes_internas')
        batch_op.drop_column('observacoes_cliente')
        batch_op.drop_column('servico_executado')
        batch_op.drop_column('problema_constatado')
        batch_op.drop_column('tecnico_responsavel')
        batch_op.drop_column('numero_de_serie')

    # ### end Alembic commands ###
