"""Adiciona campo de clausulas ao Contrato

Revision ID: cd9e4e19aa4c
Revises: 3d04be459834
Create Date: 2025-10-08 14:28:00.110453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9e4e19aa4c'
down_revision = '3d04be459834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clausulas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('clausulas')

    # ### end Alembic commands ###
