"""empty message

Revision ID: cf6aa1c07188
Revises: 
Create Date: 2025-09-24 09:40:12.640281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6aa1c07188'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('username_cliente', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('telefone_celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_auxiliar', sa.String(length=20), nullable=True),
    sa.Column('tipo_cliente', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=True),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username_cliente')
    )
    op.create_table('peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_peca', sa.String(length=100), nullable=False),
    sa.Column('detalhes_opcional', sa.Text(), nullable=True),
    sa.Column('codigo_interno', sa.String(length=100), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_peca', name='uq_peca_nome')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao_servico', sa.String(length=150), nullable=False),
    sa.Column('detalhes_opcional', sa.Text(), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao_servico', name='uq_servico_descricao')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ordem_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_sequencial', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('equipamento', sa.String(length=150), nullable=False),
    sa.Column('defeito', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_cobrado', sa.Float(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('peca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['peca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_cobrado', sa.Float(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordem_servico.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_servico')
    op.drop_table('item_peca')
    op.drop_table('ordem_servico')
    op.drop_table('usuario')
    op.drop_table('servico')
    op.drop_table('peca')
    op.drop_table('cliente')
    # ### end Alembic commands ###
