"""criado Orcamento itemservico itempeca do orcamento

Revision ID: d4f6d020e662
Revises: 29923cd778a1
Create Date: 2025-10-01 09:47:22.566142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f6d020e662'
down_revision = '29923cd778a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('equipamento', sa.String(length=150), nullable=False),
    sa.Column('numero_de_serie', sa.String(length=100), nullable=True),
    sa.Column('validade_do_orcamento', sa.String(length=100), nullable=True),
    sa.Column('problema_informado', sa.Text(), nullable=False),
    sa.Column('problema_constatado', sa.Text(), nullable=False),
    sa.Column('observacoes_cliente', sa.Text(), nullable=True),
    sa.Column('observacoes_internas', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tecnico_responsavel', sa.String(length=50), nullable=True),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_orcamento_peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_cobrado', sa.Float(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('peca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['peca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_orcamento_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_cobrado', sa.Float(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_orcamento_servico')
    op.drop_table('item_orcamento_peca')
    op.drop_table('orcamento')
    # ### end Alembic commands ###
