"""remove campo clausulas

Revision ID: df846332bcec
Revises: cd9e4e19aa4c
Create Date: 2025-10-08 19:48:59.442136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df846332bcec'
down_revision = 'cd9e4e19aa4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.drop_column('clausulas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clausulas', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
