"""coluna legenda da foto

Revision ID: e60e6e1f0a6c
Revises: a050df4edbd3
Create Date: 2025-09-25 17:39:32.168720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60e6e1f0a6c'
down_revision = 'a050df4edbd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legenda', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto', schema=None) as batch_op:
        batch_op.drop_column('legenda')

    # ### end Alembic commands ###
