"""att orcamento

Revision ID: e622136d1846
Revises: d4f6d020e662
Create Date: 2025-10-01 10:33:45.367444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e622136d1846'
down_revision = 'd4f6d020e662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_orcamento', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ano', sa.Integer(), nullable=True))
        batch_op.alter_column('validade_do_orcamento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.alter_column('validade_do_orcamento',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('ano')
        batch_op.drop_column('numero_orcamento')

    # ### end Alembic commands ###
